import { BlogPost } from './types';

// Use relative path so requests go through Vite Proxy to localhost:3000
export const API_BASE_URL = '/api';

export const TRANSLATIONS = {
  zh: {
    appName: 'Hexo Editor',
    posts: '文章列表',
    assets: '素材库',
    newArticle: '新建文章',
    filterPosts: '搜索文章...',
    filterAssets: '搜索图片...',
    noPosts: '暂无文章，请在设置中配置正确的 source/_posts 路径',
    noAssets: '暂无图片',
    unsaved: '未保存',
    copyPath: '复制路径',
    saveChanges: '保存修改',
    saved: '已保存',
    editor: '编辑',
    split: '分屏',
    preview: '预览',
    markdownSource: 'Markdown 源码',
    previewTitle: '实时预览',
    settings: '设置',
    settingsTitle: '编辑器设置',
    postsDir: '文章目录 (source/_posts)',
    imgDir: '图片目录 (source/img)',
    language: '语言 / Language',
    theme: '主题 / Theme',
    cancel: '取消',
    saveConfig: '保存配置',
    deleteConfirm: '确定要删除这篇文章吗？此操作无法撤销。',
    renderingNote: '预览仅供参考，实际效果取决于 Hexo 主题。',
    uploadImg: '上传图片',
    selectPostTip: '请选择或新建一篇文章',
    createNew: '新建',
    createSuccess: '创建成功',
    deleteSuccess: '删除成功',
    pathCopied: '路径已复制',
    fileExist: '文件已存在',
    light: '浅色',
    dark: '深色',
    connectionError: '无法连接到后端服务，请确保后端已启动 (npm run dev)。',
    rename: '重命名',
    delete: '删除',
    confirmDeleteAsset: '确定要删除这张图片吗？',
    dropToUpload: '拖拽图片到此处上传',
    uploadSuccess: '上传成功',
    renameSuccess: '重命名成功',
    enterNewName: '请输入新文件名 (包含后缀):'
  },
  en: {
    appName: 'Hexo Editor',
    posts: 'Posts',
    assets: 'Assets',
    newArticle: 'New Article',
    filterPosts: 'Filter posts...',
    filterAssets: 'Filter assets...',
    noPosts: 'No posts found. Configure source/_posts path in settings.',
    noAssets: 'No assets found.',
    unsaved: 'Unsaved',
    copyPath: 'Copy Path',
    saveChanges: 'Save Changes',
    saved: 'Saved',
    editor: 'Editor',
    split: 'Split',
    preview: 'Preview',
    markdownSource: 'Markdown Source',
    previewTitle: 'Live Preview',
    settings: 'Settings',
    settingsTitle: 'Editor Settings',
    postsDir: 'Posts Directory',
    imgDir: 'Images Directory',
    language: 'Language',
    theme: 'Theme',
    cancel: 'Cancel',
    saveConfig: 'Save Configuration',
    deleteConfirm: 'Are you sure you want to delete this post? This cannot be undone.',
    renderingNote: 'Preview is approximate. Actual rendering depends on your Hexo theme.',
    uploadImg: 'Upload Image',
    selectPostTip: 'Select a post or create new',
    createNew: 'Create New',
    createSuccess: 'Created successfully',
    deleteSuccess: 'Deleted successfully',
    pathCopied: 'Path copied',
    fileExist: 'File already exists',
    light: 'Light',
    dark: 'Dark',
    connectionError: 'Cannot connect to backend. Ensure backend is running (npm run dev).',
    rename: 'Rename',
    delete: 'Delete',
    confirmDeleteAsset: 'Are you sure you want to delete this image?',
    dropToUpload: 'Drop image here to upload',
    uploadSuccess: 'Upload successful',
    renameSuccess: 'Rename successful',
    enterNewName: 'Enter new filename (including extension):'
  }
};

export const MOCK_POSTS: BlogPost[] = [];